### ISSUE TITLE
Strange thing

### ISSUE THREAD

**Issue by OPGL** [Kethen/samsung-exynos8890#6]
I wanted to flash back my Lineage Os 19.1,
i opened twrp and it froze, tried to flash twrp again, same thing, froze on Teamwin Recovery project logo

i think that OEM Lock went on, after flashing stock rom, everything fixed

**Comment by OPGL** [comment]
whole /data seems to be corrupted, fixed using thins guide: https://forum.xda-developers.com/t/how-to-fix-unable-to-mount-data-internal-storage-0mb-in-twrp-permanently.3830897/

**Comment by OPGL** [comment]
ps. this issue doesnt exist when using ubuntu recovery, only when flashing using twrp

**Comment by Kethen** [comment]
If you are in ivan’s AOSP like roms for Galaxy S7 telegram group, you can see that “twrp getting stuck at the logo” was complained about multiple times and the reason was never found. Meanwhile it is often associated with upgrading/downgrading twrp

It likely has nothing to do with ubuntu touch nor the ubports recovery, closing
