### ISSUE TITLE
unable to install with twrp 3.4.0

### ISSUE THREAD

**Issue by aimsotrash** [Kethen/samsung-exynos8890#8]
when I try to flash the zip file it says can't install the zip file as it is for hero2lte refuse to install i have attached the error and the logs below
![Screenshot_2022-09-07-08-56-54](https://user-images.githubusercontent.com/70564215/188897761-2c1cd99e-167a-4928-a6cc-e7a611cf98ad.png)
[recovery.log](https://github.com/Kethen/samsung-exynos8890/files/9506833/recovery.log)
[dmesg.log](https://github.com/Kethen/samsung-exynos8890/files/9506834/dmesg.log)

**Comment by mertcaners12** [comment]
i fixed it partially by removing the first few detection lines

**Comment by aimsotrash** [comment]
> i fixed it partially by removing the first few detection lines

Oh ok let me try that and check

Edit1: was able to flash the zip by removing that line of code but something went wrong during installation as it kept rebooting at the galaxy s7 edge screen these are the steps i followed for flashing the zip i just flashed it via twrp and formatted the data after flash and then rebooted to system did I do anything wrong here?

Edit2: fixed the bootloop by extracting the zip and flashing boot.img as boot.img does not get installed when flashing the zip

**Comment by Kethen** [comment]
odd, where did you find your twrp, because it seem that it lacks ro.vendor.product.device= in /default.prop?
you can find the latest twrp here

flat: https://twrp.me/samsung/samsunggalaxys7.html
edge: https://twrp.me/samsung/samsunggalaxys7edge.html

on another note, the ubport installer supports the s7s now

Edit: I found this in your log `Starting TWRP 3.4.0-AJ-349ea555-dirty on Wed Sep  7 13:55:38 2022`, that is why the device detection failed, please update your twrp, the latest version is `twrp-3.6.2_9-0` as of today

3.4.0 was released more than two years ago
